#pragma once
#include <Windows.h>

#define CTRL_NUMB 0
#define CTRL_OK 0x01
#define CTRL_CANCEL 0x02

#define CTRL_EDIT_POS_X 0x11
#define CTRL_EDIT_POS_Y 0x12
#define CTRL_EDIT_SELF_NEED 0x13
#define CTRL_EDIT_SELF_CAPABILITIES 0x14

#define CTRL_EDIT_TEXT_G1 0x21
#define CTRL_EDIT_TEXT_G2 0x22

#define CTRL_EDIT_TEXT_KF 0x31
#define CTRL_EDIT_TEXT_TABOO_MAX_SIZE 0x32
#define CTRL_EDIT_TEXT_MAX_ITERATIONS 0x33
#define CTRL_EDIT_TEXT_EXPORT_PATH 0x34

#define CTRL_LISTBOX 0x41
#define CTRL_EDIT_TEXT_CAPACITY 0x42
#define CTRL_EDIT_TEXT_PRICE 0x43
#define CTRL_ADD_PIPE_TYPE 0x44
#define CTRL_DEL_PIPE_TYPE 0x45

